###Finn the human survey play

####Data
```{r, data, warning=FALSE, message=FALSE}
library(tidyverse)
#read in 2016
data.2016 <- read_csv("data/5081.survey.1.csv")
data.2016

#read in 2018
data.2018 <- read_csv("data/5081.survey.2.csv")
data.2018

#combine years
data <- bind_rows(data.2016, data.2018)
data
#write_csv(data, "data/data.combined.csv")

#play with wrangling
ecologists <- data %>%
  filter(discipline == "ecology") %>%
  select(-r.studio)
ecologists

#summary data
summary.data <- data %>%
  group_by(discipline) %>%
  count(research.data)
summary.data

summary.data <- data %>%
  group_by(year, discipline) %>%
  count(research.data)
summary.data
```

###Viz  
```{r, viz, warning=FALSE, message=FALSE}
#plot by discipline but ignores year
ggplot(data, aes(as.character(r.experience))) +
  geom_histogram(stat = "count") +
  labs(x= "reported experience in r", y = "frequency") +
 facet_wrap(~discipline) + 
  scale_x_discrete(limits = c("1", "2", "3", "4", "5"))

#includes year
ggplot(data, aes(as.character(r.experience), fill = discipline)) +
  geom_histogram(stat = "count") +
  labs(x= "reported experience in r", y = "frequency") +
 facet_wrap(~year) + 
  scale_x_discrete(limits = c("1", "2", "3", "4", "5"))
  


```